site_name: La brecha en el muro
site_description: Este blog es el lugar donde conecto los principios sólidos de la ingeniería con las posibilidades infinitas del software.
site_author: PhD. Vladímir Rodríguez Diez
repo_url: https://github.com/vladimir1284/blog
edit_uri: edit/main/docs/
theme:
  logo: assets/img/logo.png
  name: material
  font:
    text: Montserrat
  palette:
    primary: deep purple
    accent: purple
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky 
  - navigation.sections
  - navigation.top
  - navigation.footer
  - toc.follow
  - content.tooltips
  - content.code.annotate
plugins:
  - search
  - mermaid2
  - blog
extra_css:
- assets/css/style.css
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - attr_list
nav:
  - Home: blog/index.md